# require REST Client

# 
POST http://localhost:8000/mocrat_discord/api/v1/post_text/ HTTP/1.1
content-type: application/json

{
    "discord_webhook_url": "",
    "text": "This is test."
}

###
# chibamoku user get
GET http://localhost:8000/mocrat_user/api/v1/chibamoku-user/ HTTP/1.1
content-type: application/json

###
# chibamoku user get specific
GET http://localhost:8000/mocrat_user/api/v1/chibamoku-user/7245389194500509/ HTTP/1.1
content-type: application/json

###
# chibamoku user create
POST http://localhost:8000/mocrat_user/api/v1/chibamoku-user/ HTTP/1.1
content-type: application/json

{
    "discord_id" : 7245389194500509,
    "display_name" : "sample2"
}

###
# chibamoku user update
PUT http://localhost:8000/mocrat_user/api/v1/chibamoku-user/7245389194500509/ HTTP/1.1
content-type: application/json

{
    "discord_id" : 7245389194500509,
    "display_name" : "sample2",
    "level" : 2,
    "total_exp": 500
}

###
# chibamoku activity logs
GET http://localhost:8000/mocrat_user/api/v1/chibamoku-activity-logs/ HTTP/1.1
content-type: application/json
